services:
#  web:
  #    container_name: web
  #    build:
  #      context: ./frontend
  #      dockerfile: Dockerfile
  #    ports:
  #      - 3000:3000
  #    environment:
  #      - HOST=host.docker.internal
  #    depends_on:
  #      - server
  #      - db
  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=framer
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=framer
    volumes:
      - ./db/data:/var/lib/postgresql/data
#      - ./db/init/sql:/docker-entrypoint-initdb.d/create_tables.sql