services:
  web:
    container_name: web
    build:
      context: ./frontend
      dockerfile: bun.dockerfile
    ports:
      - 3000:3000
    environment:
      - CONTAINER_HOST=docker
  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080